# Deployment for running a single Concordium Rosetta instance.
# The deployment supports all the usual env vars of the service.
#
# Most values are passed directly to the service with no default values.
# A few are slightly redefined as follows:
#
# - The value of `CONCORDIUM_ROSETTA_GRPC_HOST` defaults to `172.17.0.1`,
#   i.e. a node running on the container's host.
# - The value of `CONCORDIUM_ROSETTA_PORT` only determines the port exposed to the host.
#   The internal port is hard-coded to 8080.
#   The default value of the exposed port is still 8080.
#
# The image containing the application is set using `CONCORDIUM_ROSETTA_IMAGE`.
# If this value isn't provided it will default to an image that doesn't exist in the public repo,
# which will cause Compose to build the image from source.
#
# Finally, `CONCORDIUM_ROSETTA_NETWORK` has no default value so must be set explicitly.
#
# Example:
#
#   CONCORDIUM_ROSETTA_IMAGE=concordium/rosetta:0.7.0-0 \
#   CONCORDIUM_ROSETTA_GRPC_HOST=node.mainnet.concordium.example.com \
#   CONCORDIUM_ROSETTA_NETWORK=mainnet \
#   docker-compose up -d

version: '3'
services:
  rosetta:
    container_name: rosetta
    build:
      context: .
      args:
        build_image: ${BUILD_IMAGE-rust:1.62-slim-buster}
        base_image: ${BASE_IMAGE-debian:buster-slim}
    image: ${CONCORDIUM_ROSETTA_IMAGE-concordium/rosetta:test}
    environment:
    - CONCORDIUM_ROSETTA_GRPC_HOST=${CONCORDIUM_ROSETTA_GRPC_HOST-172.17.0.1}
    - CONCORDIUM_ROSETTA_GRPC_PORT
    - CONCORDIUM_ROSETTA_GRPC_TOKEN
    - CONCORDIUM_ROSETTA_NETWORK
    - CONCORDIUM_ROSETTA_PORT=8080
    ports: # alternative: use "network_mode: host"
    - "${CONCORDIUM_ROSETTA_PORT-8080}:8080"
    stop_signal: SIGKILL
