[package]
name = "sign-transaction-hash"
version = "0.1.0"
edition = "2018"

[dependencies.concordium-rust-sdk]
path = "../../concordium-rust-sdk"
version = "*"

[dependencies]
anyhow = "1"
hex = "0.4"
serde_json = "1.0"
