[package]
name = "query-account"
version = "0.1.0"
edition = "2018"

[dependencies.rosetta]
path = "../../rosetta"
version = "*"

[dependencies]
anyhow = "1"
clap = { version = "3.1", features = ["derive"] }
reqwest = { version = "0.11", features = ["blocking", "json"] }
