[package]
name = "query-account"
version = "0.2.2"
edition = "2024"

[dependencies.rosetta]
path = "../../rosetta"

[dependencies]
anyhow = "1"
clap = { version = "=3.1", features = ["derive"] }
reqwest = { version = "0.12", features = ["blocking", "json"] }
