name: Fmt and Clippy

# Run 'rustfmt' and 'clippy' linting.

on:
  push:
    branches: main

  pull_request:
    branches: main

  workflow_dispatch: # allow manual trigger

env:
  RUST_FMT: nightly-2022-06-09-x86_64-unknown-linux-gnu
  RUST_TOOLCHAIN: 1.62

jobs:
  fmt:
    name: lint:fmt
    # Skip for draft pull requests.
    if: ${{ !github.event.pull_request.draft }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ env.RUST_FMT }}
          override: true
          components: rustfmt
      - name: Format
        run: |
          cargo fmt -- --color=always --check
      - name: Format (query-account)
        run: |
          cargo fmt --manifest-path=./tools/query-account/Cargo.toml -- --color=always --check
      - name: Format (transfer-client)
        run: |
          cargo fmt --manifest-path=./tools/transfer-client/Cargo.toml -- --color=always --check
      - name: Format (transfer-client-direct)
        run: |
          cargo fmt --manifest-path=./tools/transfer-client-direct/Cargo.toml -- --color=always --check

  clippy:
    name: lint:clippy
    needs: fmt
    # Skip for draft pull requests.
    if: ${{ !github.event.pull_request.draft }}
    runs-on: ubuntu-latest
    steps:
      - name: Install protobuf
        run: |
          wget https://github.com/protocolbuffers/protobuf/releases/download/v3.15.3/protoc-3.15.3-linux-x86_64.zip
          unzip protoc-3.15.3-linux-x86_64.zip
          sudo mv ./bin/protoc /usr/bin/protoc
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ env.RUST_TOOLCHAIN }}
          override: true
          target: ${{ env.TARGET }}
          components: rustfmt, clippy
      - name: Clippy
        run: |
          cargo clippy --color=always --tests --benches -- -Dclippy::all
      - name: Clippy (query-account)
        run: |
          cargo clippy --color=always --tests --benches --manifest-path=./tools/query-account/Cargo.toml -- -Dclippy::all
      - name: Clippy (transfer-client)
        run: |
          cargo clippy --color=always --tests --benches --manifest-path=./tools/transfer-client/Cargo.toml -- -Dclippy::all
      - name: Clippy (transfer-client-direct)
        run: |
          cargo clippy --color=always --tests --benches --manifest-path=./tools/transfer-client-direct/Cargo.toml -- -Dclippy::all
